services:
  - type: web
    name: mikka-music
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MP3_API_KEY
        sync: false
      - key: YOUTUBE_COOKIES
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: DISCORD_PREFIX
        value: "?"
      - key: NODE_ENV
        value: production
